### ISSUE TITLE
drawable问题

### ISSUE THREAD

**Issue by shiweibsw** [chenBingX/SuperTextView#1]
大多数情况下可能会把它作为一个按钮使用，如何不通过添加style文件实现按钮的点击效果呢？

**Comment by chenBingX** [comment]
如果只需要变色的话可以在代码中动态设置属性即可。
如果稍微复杂点的可以使用Adjuster来实现，当然这会稍微复杂点，但是更灵活，文档中的RippleAdjuster就是一个点击效果。
需要注意一点，原生的android:background会出现在SuperTextView自己的背景层下方。而android:drawableXXX和文字层同级。
