### ISSUE TITLE
stv_state_drawable2_layer無效

### ISSUE THREAD

**Issue by YRowis** [chenBingX/SuperTextView#100]
width設爲 match，gravity 設爲center。

**Comment by mtj956052456** [comment]
设置无效

**Comment by YRowis** [comment]
问题是width设为match，gravity设为center的情况下stv_state_drawable2_layer无效。bor。

**Comment by YRowis** [comment]
> 设置无效

**Comment by YRowis** [comment]
问题是width设为match，gravity设为center的情况下stv_state_drawable2_layer无效。bor。
