### ISSUE TITLE
做的很好用，只可惜不能设置圆角图片做背景

### ISSUE THREAD

**Issue by rmtic** [chenBingX/SuperTextView#14]
目前，圆角只能设置背景色和渐变，却无法设置圆角的背景图

**Comment by chenBingX** [comment]
感谢你的支持！
你的建议很好，在后面的版本中我会提供相关的支持的。
希望你能给身边朋友同事也推荐下SuperTextView哦😉

**Comment by rmtic** [comment]
我会推荐的，希望能快点出！

**Comment by chenBingX** [comment]
在最新版的SuperTextView已经支持了哦
