### ISSUE TITLE
当同时设置了android:singleLine="true"， android:gravity="center"之后，很多app设置的效果都没有了

### ISSUE THREAD

**Issue by littlezan** [chenBingX/SuperTextView#18]
corner， solid 什么效果都没有了

没有设置:
![image](https://user-images.githubusercontent.com/5358278/30640090-199de016-9e34-11e7-974b-7619bab0030b.png)

设置`android:singleLine="true"` 和 `android:gravity="center"` 之后：
![image](https://user-images.githubusercontent.com/5358278/30640168-67c27d92-9e34-11e7-950b-368dfcb56dea.png)

**Comment by chenBingX** [comment]
感谢你的反馈。请暂时先用lines="1"代替。

**Comment by chenBingX** [comment]
您好，
在 v3.1.4 版本中，这个问题已经得到了修复，建议升级到此版本。
  感谢您的支持！❤️
