### ISSUE TITLE
superTextview如何加载网络图片作为背景呢

### ISSUE THREAD

**Issue by waitingyc** [chenBingX/SuperTextView#21]
superTextview如何加载网络图片作为背景呢

**Comment by chenBingX** [comment]
目前只能自己下载好图片，然后放到SuperTextView中作为背景。

**Comment by chenBingX** [comment]
我目前正在构想让SuperTextView可以展示网络一些类型的数据，也许下个版本你就能体验加载网络图作为背景的功能了。
