### ISSUE TITLE
我引用了一个视图框架，再集成就成这个样子了

### ISSUE THREAD

**Issue by LeslieKoma** [chenBingX/SuperTextView#26]
\app\build\intermediates\res\merged\debug\values\values.xml
Error:(439) Attribute "stroke_width" already defined with incompatible format.
Error:(425) Original attribute defined here.
Error:(439) Attribute "stroke_width" already defined with incompatible format.
Error:(425) Original attribute defined here.

**Comment by chenBingX** [comment]
属性资源名冲突了，需要改其中一个哦

**Comment by wulijie** [comment]
你这库命名属性不规范啊 作者

**Comment by chenBingX** [comment]
您好，
 在新的 v3.1.4 版本中，SuperTextView 属性名称被加入了专有的前缀，可以解决绝大部分的冲突问题。
如果在升级过程中遇到与旧版本的兼容问题，可以参考：https://github.com/chenBingX/SuperTextView#5%EF%B8%8F-%E4%BD%A0%E5%BF%85%E9%A1%BB%E9%87%8D%E8%A7%86%E8%BF%99%E4%BA%9B%E5%8F%98%E5%8C%96
