### ISSUE TITLE
建议自定义属性名称前面加一个前缀

### ISSUE THREAD

**Issue by Carlos2927** [chenBingX/SuperTextView#27]
加前缀可以有效的防止项目中使用其它第三方库可能出现的属性重名而导致不得不下载源码更改属性名称的问题

**Comment by Carlos2927** [comment]
还有问作者一个问题，你的项目跟另外一个 [SupperTextView](https://github.com/lygttpod/SuperTextView)很像啊 刚开始还弄错了  实现机制也大不一样

**Comment by chenBingX** [comment]
您好，
在新版的 v3.1.4 中，解决了命名冲突的问题，建议升级到该版本。
如果遇到和旧代码兼容的问题，可以参考：https://github.com/chenBingX/SuperTextView#5%EF%B8%8F-%E4%BD%A0%E5%BF%85%E9%A1%BB%E9%87%8D%E8%A7%86%E8%BF%99%E4%BA%9B%E5%8F%98%E5%8C%96

   感谢您的支持！❤️
