### ISSUE TITLE
希望增强对CompoundDrawable的功能

### ISSUE THREAD

**Issue by Carlos2927** [chenBingX/SuperTextView#28]
如对于设置的android:drawableLeft有app:drawableLeftScale = 0.8来控制其缩放比例，对于文本与CompoundDrawable的距离不受宽度设置为match_parent影响，增加app:drawableLeftPressedColor,app:drawableLeftPressedDrawable等属性

**Comment by chenBingX** [comment]
您好，
目前，最新版本的 SuperTextView v3.1.4 已经能够满足您的需求，建议升级到此版本。
