### ISSUE TITLE
ripple效果在小米6.0上扩散到最后卡住不动

### ISSUE THREAD

**Issue by hss01248** [chenBingX/SuperTextView#3]

**Comment by chenBingX** [comment]
我Demo也是在小米4 Android 6.0，但是没有出现这个问题。你可以提供再多点的信息吗？

**Comment by Carlos2927** [comment]
@chenBingX 小米A1 Android 8.0也是一样的现象

**Comment by chenBingX** [comment]
@Carlos2927 此处的 Ripple 是写成这样，仅仅是为了展示效果，所以没有做更多的处理
