### ISSUE TITLE
文字怎么设置渐变色

### ISSUE THREAD

**Issue by LelandLi** [chenBingX/SuperTextView#33]
文字怎么设置渐变色

**Comment by chenBingX** [comment]
目前不支持渐变色哈

**Comment by chenBingX** [comment]
您好，
在最新的 v3.1.4 版本中，支持了文字渐变色的功能。
使用可以参考：https://github.com/chenBingX/SuperTextView#3-%E7%B2%BE%E5%BD%A9%E8%BF%9C%E4%B8%8D%E6%AD%A2%E4%BA%8E%E6%AD%A4
