### ISSUE TITLE
stv:sLeftTextString=  一行长文字 显示不下

### ISSUE THREAD

**Issue by SomnusWu** [chenBingX/SuperTextView#34]
stv:sLeftTextString=“长文字~~~~”
类似这个布局 ，文字很长的时候
![tim 20181017105116](https://user-images.githubusercontent.com/7221064/47059174-b431ec80-d1fa-11e8-913e-1fbc5723dbf3.png)

**Comment by chenBingX** [comment]
你好，你可能使用的不是这个 SuperTextView
