### ISSUE TITLE
 3.1.1 依赖冲突

### ISSUE THREAD

**Issue by liaoshengrui** [chenBingX/SuperTextView#35]
AGPBI: {"kind":"error","text":"Program type already present: com.coorchice.library.BuildConfig","sources":[{}],"tool":"D8"}

3.1.1报这个  3.0.0正常使用
没发现是哪个依赖冲突了

**Comment by chuwe1** [comment]
@chenBingX README中 一些图 烂了

**Comment by chenBingX** [comment]
@chuwe1 您好，
感谢提醒，由于此前图库被关闭，导致部分图片链接失效，现在已经重新更新了图片。
  感谢您的支持！💗
