### ISSUE TITLE
新的库能用以前的方法吗？

### ISSUE THREAD

**Issue by 183883324** [chenBingX/SuperTextView#37]
新的能用2.0的api吗？

**Comment by 183883324** [comment]
之前的不能用了，不如做两个库，为什么非要我2选1呢 。 。 。 。 。。

**Comment by chenBingX** [comment]
您好，
抱歉，新的版本具备了旧版所有的特性，可能部分 api 的调用略有调整，建议升级到新版本后，通过 AndroidStudio 的批量替换功能进行更新。
可以参考：https://github.com/chenBingX/SuperTextView#5%EF%B8%8F-%E4%BD%A0%E5%BF%85%E9%A1%BB%E9%87%8D%E8%A7%86%E8%BF%99%E4%BA%9B%E5%8F%98%E5%8C%96
