### ISSUE TITLE
为什么onDraw方法里面有时候会报错 因为控件尺寸为0导致的

### ISSUE THREAD

**Issue by Carlos2927** [chenBingX/SuperTextView#38]
![default](https://user-images.githubusercontent.com/12493233/50955720-d46d0100-14f4-11e9-834b-58bd474cad71.png)
![default](https://user-images.githubusercontent.com/12493233/50955779-f23a6600-14f4-11e9-85a9-575707756c9a.png)

**Comment by chenBingX** [comment]
Hi，你好，
  感谢使用 SuperTextView，你反馈的问题 CoorChice 在持续跟进。  
  
  目前发布了最新版 v3.1.5 中修复了这个问题，建议更新到最新版本。  

  替换 build.gradle 中的依赖为：  

  ```
  dependencies {
	        implementation 'com.github.chenBingX:SuperTextView:3.1.5'
	}
  ```
