### ISSUE TITLE
加载网络图片时，怎么设置占位图呢？

### ISSUE THREAD

**Issue by zaaach** [chenBingX/SuperTextView#43]

**Comment by zaaach** [comment]
<shape xmlns:android="http://schemas.android.com/apk/res/android" android:shape="rectangle">
    <solid android:color="@color/placeholder_bg"/>
</shape>
占位图是这样的，会报错

**Comment by chenBingX** [comment]
Hi，你好，
  感谢使用 SuperTextView，你反馈的问题 CoorChice 在持续跟进。  
  
  目前发布了最新版 v3.1.5 中修复了这个问题，建议更新到最新版本。  

  替换 build.gradle 中的依赖为：  

  ```
  dependencies {
	        implementation 'com.github.chenBingX:SuperTextView:3.1.5'
	}
  ```
