### ISSUE TITLE
是否可以加入图片转动的属性（代码可以控制转动属性的显隐和开始停止）

### ISSUE THREAD

**Issue by xyZangGit** [chenBingX/SuperTextView#46]
比如：等待网络请求图片的转动

**Comment by chenBingX** [comment]
目前暂时无集成此类定制化效果的计划哦。  

你可以使用 Adjuster 或是原生动画去实现此类效果哦。  

关于 Adjuster 的使用，可以参考：  

  [万能的Adjuster](https://github.com/chenBingX/SuperTextView/wiki/%E4%B8%87%E8%83%BD%E7%9A%84Adjuster)
