### ISSUE TITLE
动态设置 text有时会不显示问题（小米机型出现，华为手机未出现）

### ISSUE THREAD

**Issue by xyZangGit** [chenBingX/SuperTextView#47]
if ("已预约".equals(text) || "服务次数已用完".equals(text)) {
            mServiceDetailAppointmentStv.setTextColor(getContext().getResources().getColor(R.color.colorSubhead));
            mServiceDetailAppointmentStv.setStrokeColor(getContext().getResources().getColor(R.color.colorSubhead));
            mServiceDetailAppointmentStv.setText(text);

颜色设置生效，text设置不显示， 
机型：android9.0+小米mix2s+MIUI10稳定版   出现文字不显示问题
华为荣耀8X  android8.0  没有出现过这样的问题
使用版本为 api 'com.github.chenBingX:SuperTextView:v3.1.1'

**Comment by chenBingX** [comment]
感谢您的反馈，我后面会跟进这个问题。

建议先升级到最新版，看看这个问题是否仍然存在。

替换 build.gradle 中的依赖为：
```
dependencies {
          implementation 'com.github.chenBingX:SuperTextView:3.1.5'
  }
```

**Comment by xyZangGit** [comment]
已经升级到最新版本了，还是有这个问题

**Comment by chenBingX** [comment]
我尝试了几个 9.0 的机器，没有复现这个问题。  

我没有 `android9.0+小米mix2s+MIUI10稳定版` 的设备。  

你能把 `mServiceDetailAppointmentStv` 更详细的配置让我看一下吗？

**Comment by xyZangGit** [comment]
原生的textview也有这个问题，应该是是弹窗的问题；
