### ISSUE TITLE
addAdjuster Animation speed

### ISSUE THREAD

**Issue by Zvirtuey** [chenBingX/SuperTextView#49]
能不能设置Adjuster的动画速度！现在好像是1秒，能给个设置的接口么？

**Comment by chenBingX** [comment]
您好： 

Adjuster 的使用可以参考：  https://github.com/chenBingX/SuperTextView/wiki/%E4%B8%87%E8%83%BD%E7%9A%84Adjuster

通过以下方法，开发者可以随时修改 SuperTextView 的刷新频率：
```
// 每秒30帧
stv.setFrameRate(30);
```

**Comment by Zvirtuey** [comment]
不是扫码帧率，是多少时间一扫描，我想三十秒或者一分钟秒来一次动画，帧率任然可以是60帧 但是就是时间间隔长一点。

**Comment by chenBingX** [comment]
通过 `stv.startAnim()` 和 `stv.stopAnim()` 可以启动或者停止动画，然后你可以借助线程、或者一个延时任务来根据需求控制启动、停止你的动画。

**Comment by Zvirtuey** [comment]
我也想过自己定时刷，但是要在动画刷完才停止，不能刷到一半就stop，我得知道什么时候刷完，然后stop，在过一会start！有监听执行动画的接口么
