### ISSUE TITLE
问个问题。我怎么用本地图片替换网络加载的图片？

### ISSUE THREAD

**Issue by guoleifei** [chenBingX/SuperTextView#50]
问个问题。我怎么用本地图片替换网络加载的图片？
因为我的图片如果是没有头像 就本地的一个图片
有头像就网络加载。

![image](https://user-images.githubusercontent.com/16201257/54602790-91dc1d80-4a7d-11e9-94bf-63ffdf88af75.png)
这个是我们有头像和没有头像时的ui
我把没头像的时候设置的边框做成了shape 因为边框设置渐变貌似没效果
 有头像的时候是外面的有头像圆角设计

**Comment by chenBingX** [comment]
您好，
 目前仅支持 `drawableAsBackground = false`，设置默认图片。  
 但现在你可以这样处理，在有该需求的地方，你可以先设置默认图片，然后使用图片加载框架加载到图片，接着通过 `setDrawable()` 再设置到你的SuperTextView上。  

参考：https://github.com/chenBingX/SuperTextView/wiki/%E5%B1%95%E7%A4%BA%E5%9B%BE%E7%89%87#%E5%B1%95%E7%A4%BA%E7%BD%91%E7%BB%9C%E5%9B%BE%E7%89%87

**Comment by guoleifei** [comment]
这样做的话。。在recycleview里 view 复用会出问题。

**Comment by guoleifei** [comment]
已解决。
