### ISSUE TITLE
有没有类似unableBgColor这样的属性？

### ISSUE THREAD

**Issue by pangyu646182805** [chenBingX/SuperTextView#52]
请问有没有类似unableBgColor这样的属性？

**Comment by chenBingX** [comment]
你好，
  目前没有这个属性。你可以根据当前所需状态设置solid属性。  
  可以参考：[附录：属性大全](https://github.com/chenBingX/SuperTextView/wiki/%E9%99%84%E5%BD%95%EF%BC%9A%E5%B1%9E%E6%80%A7%E5%A4%A7%E5%85%A8)
