### ISSUE TITLE
建议加上悬浮阴影效果

### ISSUE THREAD

**Issue by a1227308812** [chenBingX/SuperTextView#53]
建议加上悬浮阴影效果，类似于cardview的那种阴影，高版本的原生button都自带有发散效果，用了stv去代替button，节省了写selecter的时间，但是缺失了阴影效果，建议作者后期可以加上。谢谢！！！

**Comment by chenBingX** [comment]
您好呀开发者：
感谢您的建议，由于高版本系统api权限的收紧，阴影效果实现方案不是太容易，传统的做法效果也不是太好。
目前，你可以十分谨慎的尝试一下 `elevation` 属性。
