### ISSUE TITLE
文字和图片怎么同时居中

### ISSUE THREAD

**Issue by huchenguang** [chenBingX/SuperTextView#54]
就是我在使用SuperTextView想实现  让图标显示在文字的左边，间距10dp，这样。   我看demo里都是手动计算的，很多情况下并不能确定计算出来

**Comment by chenBingX** [comment]
您好呀开发者：
   截止目前，只能通过计算实现。
   由于目前SuperTextView承载的能力比较多，互相之间会有相互作用，居中的实现我会谨慎思考的。
   如在使用状态图的过程中有疑问，可参考：[点击跳转](https://github.com/chenBingX/SuperTextView/wiki/%E7%8A%B6%E6%80%81%E5%9B%BE)
