### ISSUE TITLE
一个小问题

### ISSUE THREAD

**Issue by ruanbaojun1105** [chenBingX/SuperTextView#59]
首先感谢作者

控件在设置文字颜色的时候有效，但是在控件被触摸的时候字体颜色又被还原了~~~~

**Comment by chenBingX** [comment]
是不是设置了文字按压变色的属性？

**Comment by ruanbaojun1105** [comment]
@chenBingX 是的

**Comment by chenBingX** [comment]
设置了按压变色的属性，触摸的时候就是会改变颜色哦！
建议参考：[https://github.com/chenBingX/SuperTextView/wiki/%E6%8C%89%E5%8E%8B%E5%8F%98%E8%89%B2](https://github.com/chenBingX/SuperTextView/wiki/%E6%8C%89%E5%8E%8B%E5%8F%98%E8%89%B2)

**Comment by ruanbaojun1105** [comment]
@chenBingX 我的意思是：设置了按压变色状态下，再去设置文字颜色，当手按下控件是按压的颜色，但是手抬起来后却显示的不是我设置的文字颜色，而显示成了按压色~

**Comment by ruanbaojun1105** [comment]
这个bug每个版本都有~~竟然~~~~关了？

**Comment by Dullyoung** [comment]
这个bug在v3.2.5.99中依然存在，复现方法：在recyclerview中使用stv，如下代码，重复点击同一个item时就会出现此问题。
```java
       boolean isSelect;


        if (info.isSelect()) {
            stv.setSolid(getColor(R.color.theme));
            stv.setTextColor(Color.WHITE);
        }else {
            stv.setSolid(Color.TRANSPARENT);
            stv.setTextColor(Color.BLACK));
        }


mAdapter.setOnItemChildClickListener((adapter, view, position) -> {
   mAdapter.getItem(position).setSelect(true);
   mAdapter.notifyItemChanged(i);
  });

```
