### ISSUE TITLE
提个建议

### ISSUE THREAD

**Issue by songsongtao** [chenBingX/SuperTextView#6]
1.只支持4.4以上，公司开发的话应该用不了
2.图片和文字居中的情况还是不好用
3.最好能提供默认的点击效果
其它感觉都很完美

**Comment by chenBingX** [comment]
感谢你的支持。
我已经发布了v1.1版本，最低可以支持到4.0。
关于图片和文字的居中是什么问题呢？
由于需求不同，默认的点击效果可能会造成部分开发者有时候不得不去关闭默认点击效果的困惑。

感谢你提出的建议。
