### ISSUE TITLE
透明gif渲染问题？

### ISSUE THREAD

**Issue by DCRain** [chenBingX/SuperTextView#63]
版本：3.2.1
手机系统：小米8 miui 10
透明gif渲染问题，见图
原始gif：
![image](https://user-images.githubusercontent.com/6848397/64938065-30abd000-d88f-11e9-8db3-09d07dba200e.png)

渲染后的样子：
![image](https://user-images.githubusercontent.com/6848397/64937975-e0cd0900-d88e-11e9-8d9f-f66862f84b51.png)

代码如下：
![image](https://user-images.githubusercontent.com/6848397/64937990-f4786f80-d88e-11e9-9797-4677a1968f13.png)
![image](https://user-images.githubusercontent.com/6848397/64937999-f9d5ba00-d88e-11e9-8d9c-da3f08e902d2.png)

**Comment by chenBingX** [comment]
在最新的 v3.2.3 版本中，这个问题已经得到修复哦
