### ISSUE TITLE
老哥 你的so库能不能加上x86的支持 

### ISSUE THREAD

**Issue by moneeWong** [chenBingX/SuperTextView#66]

**Comment by moneeWong** [comment]
还有armeabi，能支持所有设备岂不美哉

**Comment by moneeWong** [comment]
欸？我看你的提交记录里增加了x86啊，文件咋没有呢

**Comment by chenBingX** [comment]
啊，x86的设备太少了，x86包比较大，会增加体积的。你需要的话我给你单独发个x86的so

**Comment by moneeWong** [comment]
> 啊，x86的设备太少了，x86包比较大，会增加体积的。你需要的话我给你单独发个x86的so

好的，请发664846442@qq.com，感谢
不过还是建议在项目中加上，哪怕新开个分支作为完整版也好，不然估计有人会折在这个问题上，平板上x86还是不少的，模拟器开发也是个问题，你总不能挨个发so库吧，个人觉得在这种问题上兼容性更重要些，如果在意size的话，建议把gif功能抽离出来作为支持库，祝更好

**Comment by ruanbaojun1105** [comment]
确实应该加上x86，如果不使用，我们会自己过滤掉。

**Comment by chenBingX** [comment]
感谢建议，我开个后面开个新分支吧。

**Comment by chenBingX** [comment]
hi，目前，在 `3.2.5` 系列版本中， `3.2.5.99` 分支已经支持了 **x86**，一些问题也得到了修复，欢迎更新使用😄
