### ISSUE TITLE
gif的加载性能没有glide给力

### ISSUE THREAD

**Issue by ruanbaojun1105** [chenBingX/SuperTextView#68]

**Comment by chenBingX** [comment]
Glide 在首次加载后会对加载解析结果进行缓存，Glide 首次加载大Gif耗时是很长的。
SuperTextView 首次加载大 Gif 会比 Glide 快很多哦 😏
SuperTextView 后续也会考虑对 Gif 的解析结果进行缓存，欢迎保持关注
