### ISSUE TITLE
版本改来改去，好多基础功能都失效了

### ISSUE THREAD

**Issue by ruanbaojun1105** [chenBingX/SuperTextView#69]
是必须设置了什么属性这个stv_pressBgColor的才有效呢？？？？而且以前版本按住后抬起就会不显示stv_pressBgColor，这几个版本都是按住抬起后还是stv_pressBgColor，请增加功能的同时别把基础功能做没了~~~

**Comment by ruanbaojun1105** [comment]
而且，setOnDrawableClickedListener这个新事件在设置了padding_top="210dp"、padding_left="-60dp"，这两个属性后点击事件根本识别不了，，，我的天~

**Comment by chenBingX** [comment]
> 是必须设置了什么属性这个stv_pressBgColor的才有效呢？？？？而且以前版本按住后抬起就会不显示stv_pressBgColor，这几个版本都是按住抬起后还是stv_pressBgColor，请增加功能的同时别把基础功能做没了~~~

噢😯，这个功能暂时失效了，后续会发布相关修复版本。
      欢迎保持关注😊

**Comment by chenBingX** [comment]
> 而且，setOnDrawableClickedListener这个新事件在设置了padding_top="210dp"、padding_left="-60dp"，这两个属性后点击事件根本识别不了，，，我的天~

方便贴出完整代码吗？因为在我的尝试中，setOnDrawableClickedListener 依旧在有效的工作。

**Comment by chenBingX** [comment]
hi，在最新的 `3.2.5` 版本中，你发现的这些问题已经得到修复。希望 SuperTextView 能继续为你带来高效且愉悦的开发体验 😊
