### ISSUE TITLE
页面退到后台再回到前台动画停止播放

### ISSUE THREAD

**Issue by christian-zs** [chenBingX/SuperTextView#7]
1、页面退到后台再回到前台动画停止播放

**Comment by christian-zs** [comment]
@Override
    protected void onWindowVisibilityChanged(int visibility) {
        super.onWindowVisibilityChanged(visibility);
        if (visibility != VISIBLE) {
            cacheRunnableState = runnable;
            cacheNeedRunState = needRun;
            stopAnim();
        }
        if (visibility == VISIBLE) { // 页面回到前台重新播放
            cacheRunnableState = true;
            cacheNeedRunState = true;
        } else if (cacheRunnableState && cacheNeedRunState) {
            startAnim();
        }
    }

**Comment by chenBingX** [comment]
感谢支持。我回头看看。

**Comment by RealMoMo** [comment]
同遇

**Comment by chenBingX** [comment]
您好，
建议升级到最新的 v3.1.4 版本。
   感谢支持❤️
