### ISSUE TITLE
Gif 不显示

### ISSUE THREAD

**Issue by TrueloveSomeGIRl** [chenBingX/SuperTextView#71]
不知道我配置没对还是什么问题 Gif不出来

![BU3YD9)OQF61I6XO9XSKTMW](https://user-images.githubusercontent.com/25426589/68555435-b8195800-0468-11ea-9742-e8e6829def4c.png)
![9D(N{$H2)(%V1P5`HATR~S5](https://user-images.githubusercontent.com/25426589/68555436-b94a8500-0468-11ea-9b15-a066c858067c.png)

**Comment by TrueloveSomeGIRl** [comment]
> 不知道我配置没对还是什么问题 Gif不出来
> 
> ![BU3YD9)OQF61I6XO9XSKTMW](https://user-images.githubusercontent.com/25426589/68555435-b8195800-0468-11ea-9742-e8e6829def4c.png)
> ![9D(N{$H2)(%V1P5`HATR~S5](https://user-images.githubusercontent.com/25426589/68555436-b94a8500-0468-11ea-9b15-a066c858067c.png)

不能支持Androidx嘛

**Comment by chenBingX** [comment]
需要添加：  

```
app:stv_isShowState="true"  
```  

开启 StateDrawable 功能
或者添加：  

```
app:stv_drawableAsBackground="true"
```

来启用 StateDrawable 作为背景图的能力。

具体可以参考：
1.https://github.com/chenBingX/SuperTextView/wiki/%E7%8A%B6%E6%80%81%E5%9B%BE
2.https://github.com/chenBingX/SuperTextView/wiki/%E5%B1%95%E7%A4%BA%E5%9B%BE%E7%89%87
