### ISSUE TITLE
3.2.5 stv_state_drawable 页面加载的时候就报错

### ISSUE THREAD

**Issue by SemiraChen** [chenBingX/SuperTextView#72]
dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.sj.shijie-ZyBYiMLhaumfKW_Hw-7IdQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.sj.shijie-ZyBYiMLhaumfKW_Hw-7IdQ==/lib/arm64, /data/app/com.sj.shijie-ZyBYiMLhaumfKW_Hw-7IdQ==/base.apk!/lib/arm64-v8a, /system/lib64]]] couldn't find "libGifLib.so"

报这个错，我把版本切换到3.1.5就没问题了

**Comment by chenBingX** [comment]
在这个情况中，你可以尝试 `3.2.5.64` 版本，它包含了 **arm64-v8a** 的 `.so` 库

**Comment by SemiraChen** [comment]
谢谢

**Comment by runnchild** [comment]
> 在这个情况中，你可以尝试 `3.2.5.64` 版本，它包含了 **arm64-v8a** 的 `.so` 库

没有x86的so库吗
