### ISSUE TITLE
stv_pressBgColor 属性使用问题

### ISSUE THREAD

**Issue by imtianx** [chenBingX/SuperTextView#78]
当设置 `enabled = false` 时，如果设置了 `stv_pressBgColor` 此时 press 还会显示设置的颜色

**Comment by chenBingX** [comment]
在 **SuperTextView** 中，enable 与触摸没有直接关系，如果你不再需要 `press color`，可以将其设置为透明色。可以参考: [【按压变色】](https://github.com/chenBingX/SuperTextView/wiki/%E6%8C%89%E5%8E%8B%E5%8F%98%E8%89%B2)
