### ISSUE TITLE
播放gif 会闪  有没有播放fgif 完成的回调呀

### ISSUE THREAD

**Issue by TrueloveSomeGIRl** [chenBingX/SuperTextView#79]

**Comment by chenBingX** [comment]
1.  gif 闪动有更详细的信息吗，设备型号和系统版本，有演示图的话会更有助于问题排查
2. 目前还没有专门针对 Gif 播放完成的回调，但你可以通过 `GifDrawable#setOnFrameListener(GifDecoder.OnFrameListener onFrameListener)`  在回调中，通过 `GifDrawable#getFrameCount()` 和  `GifDrawable#getCurrentFrame()` 来完成这样的判断。也许 https://github.com/chenBingX/SuperTextView/blob/master/app/src/main/java/com/coorchice/supertextview/GifActivity.java 文件中 #92 会对你有所帮助。
